name: CMake CI

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: labs/lab1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake make g++

      - name: Configure
        run: cmake -B build

      - name: Build
        run: cmake --build build

      - name: Run tests
        working-directory: labs/lab1/build
        run: ctest --output-on-failure
